{
 "title": "Gnoyaguer 1 monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 3, "x": 10, "y": 0 }, "options": { "content": "# Gnoyager 1 🚀👨🏼‍🚀" } },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
   "targets": [
    { "expr": "gno_latest_block_height", "legendFormat": "Block Height" }
   ]
  },
  {
   "title": "Number of transactions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gno_transactions_total", "legendFormat": "Number of transactions" }
   ]
  },
  {
   "title": "Number of different message types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gno_message_types_total", "legendFormat": "{{typeUrl}}" }
   ]
  },
  {
   "title": "Most active transaction senders",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "gno_senders_total", "legendFormat": "{{sender}}" }
   ]
  },
  {
   "title": "Number of packages deployed/called",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gno_packages_deployed_total", "legendFormat": "{{sender}}" }
   ]
  }
 ]
}