version: '3.8'
services:
  gno_node:
    build: 
      context: ./gno
      dockerfile: Dockerfile.test
    ports:
      - '26657:26657'
      - '26656:26656'
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:26657/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
  gno_indexer:
    build: 
      context: ./tx-indexer
      dockerfile: Dockerfile.test
    ports:
      - '8546:8546'
    restart: always
    depends_on:
      gno_node:
        condition: service_healthy
  gno_supernova:
    build: ./supernova
    depends_on:
      gno_node:
        condition: service_healthy
  gno_monitoring:
    build: ./gno_monitoring
    ports:
      - '2112:2112'
    depends_on:
     - gno_supernova
     - gno_indexer
  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - '9090:9090'
    volumes:
      - ./gno_monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - gno_monitoring
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
    env_file:
      - ./gno_monitoring/grafana/.env
    ports:
      - '3000:3000'
    volumes:
      - ./gno_monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./gno_monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./gno_monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus
volumes:
  data: {}
networks:
  gno_network:
